# https://github.com/codespell-project/codespell
# https://beta.ruff.rs
name: lint
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pip install --user codespell[toml] ruff
    - run: codespell
    - run: ruff --format=github .
